/**
 * SINGLE SOURCE OF TRUTH for all construction material categories.
 * To add new categories/subcategories, edit this file only.
 * All forms (RFQ creation, supplier profile) read from here.
 *
 * Data values - not translated via i18n. Add display mapping if bilingual UI needed.
 */

export const CATEGORIES_DATA: Record<string, string[]> = {
  "حديد ومعادن": [
    "حديد تسليح",
    "حديد مجلفن",
    "شبك حديد (مش)",
    "حديد مشكّل (زوايا، مواسير، صاج)",
    "صاج مضلع",
    "ستيل ستراكشر (هياكل حديدية)",
    "مسامير وبراغي ومثبتات",
    "سلك ربط",
    "حديد زهر",
  ],
  "أسمنت وخرسانة": [
    "أسمنت بورتلاندي عادي",
    "أسمنت مقاوم للكبريتات",
    "أسمنت أبيض",
    "أسمنت سريع التصلب",
    "خرسانة جاهزة",
    "خرسانة مسبقة الصب (بريكاست)",
    "إضافات خرسانية",
    "أسمنت تشطيب (لياسة)",
  ],
  "طوب وبلوك": [
    "بلوك أسمنتي مفرغ",
    "بلوك أسمنتي مصمت",
    "بلوك عازل (إنسوليت)",
    "طوب أحمر مفرغ",
    "طوب أحمر مصمت",
    "طوب أحمر حراري",
    "طوب أبيض خفيف (سيبوركس)",
    "طوب زجاجي",
  ],
  "أرضيات وتشطيبات": [
    "بورسلين",
    "سيراميك",
    "رخام طبيعي",
    "جرانيت طبيعي",
    "رخام صناعي",
    "بلاط إسمنتي",
    "بلاط إنترلوك",
    "باركيه خشبي",
    "فينيل (SPC / LVT)",
    "إيبوكسي أرضيات",
    "موزاييك",
    "حجر طبيعي",
  ],
  "أبواب ونوافذ": [
    "أبواب خشبية طبيعية (زان، سنديان)",
    "أبواب خشبية حشو (HDF)",
    "أبواب WPC",
    "أبواب PVC",
    "أبواب HPL",
    "أبواب حديد",
    "أبواب ألمنيوم",
    "أبواب مقاومة للحريق",
    "أبواب زجاجية",
    "أبواب كراجات (رول أب / سيكشنال)",
    "أبواب أكورديون",
    "نوافذ ألمنيوم",
    "نوافذ UPVC",
    "نوافذ زجاج مزدوج",
    "زجاج سيكوريت",
    "زجاج عاكس",
    "شبابيك حديد مشغول",
  ],
  "كهرباء وإنارة": [
    "أسلاك كهربائية (NYY, NYA)",
    "كابلات نحاسية",
    "مفاتيح كهربائية",
    "مقابس كهربائية",
    "لوحات توزيع كهربائية",
    "قواطع كهربائية (MCB, MCCB)",
    "مواسير كهرباء PVC",
    "مواسير كهرباء معدنية",
    "أنظمة إنارة LED",
    "كشافات إضاءة خارجية",
    "ثريات ونجف",
    "إضاءة مخفية",
    "أنظمة إنارة طوارئ",
    "أنظمة طاقة شمسية",
    "UPS وأنظمة طاقة احتياطية",
    "أنظمة إنذار حريق",
    "أنظمة كاميرات مراقبة",
    "أنظمة إنتركم وتحكم بالدخول",
  ],
  "أدوات صحية وسباكة": [
    "مواسير PPR",
    "مواسير PVC صرف",
    "مواسير نحاس",
    "مواسير حديد مجلفن",
    "خلاطات مياه",
    "أطقم حمامات (كرسي إفرنجي + مغسلة)",
    "كرسي عربي",
    "بانيو",
    "جاكوزي",
    "بيديه",
    "شطافات",
    "سخانات مياه كهربائية",
    "سخانات مياه غاز",
    "مضخات مياه",
    "خزانات مياه (فيبر / ستانلس / بولي إيثيلين)",
    "فلاتر مياه",
    "مصافي أرضيات",
    "محابس وصمامات",
  ],
  "عزل وأسقف": [
    "عزل مائي (رولات بيتومين)",
    "عزل مائي سائل",
    "عزل حراري (فوم بولي يوريثان)",
    "عزل حراري (صوف صخري)",
    "عزل حراري (بولي ستايرين XPS)",
    "عزل صوتي",
    "ألواح ساندوتش بانل",
    "أسقف معدنية",
    "أسقف قرميد",
    "ألواح بولي كربونيت",
    "مانع رطوبة",
  ],
  "دهانات وألوان": [
    "دهان بلاستيكي (مائي) داخلي",
    "دهان بلاستيكي خارجي",
    "دهان زيتي",
    "دهان إيبوكسي",
    "دهان بولي يوريثان",
    "معجون حوائط",
    "أساس (برايمر)",
    "دهان مقاوم للحريق",
    "دهان مقاوم للرطوبة",
    "رشات ديكورية (تكستشر)",
    "ورق جدران",
    "دهان أرضيات",
  ],
  "جبس وأسقف مستعارة": [
    "ألواح جبس بورد عادي",
    "ألواح جبس بورد مقاوم للرطوبة",
    "ألواح جبس بورد مقاوم للحريق",
    "جبس بلدي (جبس باريس)",
    "فواصل معدنية للجبس (أوميغا + C Channel)",
    "ألواح أسقف مستعارة (معدنية)",
    "ألواح أسقف مستعارة (فاينل)",
    "كورنيش جبس",
    "زخارف جبسية",
  ],
  "خرسانة جاهزة ومواد خام": [
    "خرسانة جاهزة عادية",
    "خرسانة جاهزة عالية المقاومة",
    "رمل غسيل",
    "رمل أبيض",
    "بحص (حصى)",
    "كنكري (ركام)",
    "تربة زراعية",
    "ردميات",
  ],
  "معدات وآليات": [
    "رافعات (كرينات)",
    "حفارات",
    "بوب كات",
    "شيول",
    "قلابات (دنبر)",
    "خلاطات خرسانة",
    "مولدات كهربائية",
    "ضواغط هواء (كمبريسر)",
    "سقالات",
    "هزازات خرسانة",
    "قوالب خرسانية (فورم ورك)",
    "بامبات خرسانة",
  ],
  "مواد لاصقة وكيميائية": [
    "لاصق بلاط (سيراميك / بورسلين)",
    "لاصق رخام",
    "مادة وقف تسرب (سيليكون)",
    "فواصل تمدد",
    "مواد تقوية خرسانة",
    "إضافات خرسانية (معجّلات / مؤخرات)",
    "مواد معالجة الخرسانة (كيورينغ)",
    "مانع تسرب بولي يوريثان",
    "غراء خشب",
  ],
  "حدادة ومصنوعات معدنية": [
    "درابزين حديد",
    "درابزين ستانلس ستيل",
    "هناجر ومستودعات",
    "بوابات حديد",
    "سلالم حديد",
    "مظلات حديد",
    "مظلات PVC",
    "حواجز أمنية",
    "أعمدة إنارة",
  ],
  "تكييف وتهوية (HVAC)": [
    "وحدات تكييف سبليت",
    "وحدات تكييف مركزي",
    "وحدات تكييف كونسيلد",
    "مجاري هواء (دكت)",
    "مراوح شفط",
    "فلاتر تكييف",
    "ثيرموستات ذكية",
    "أنظمة تبريد صحراوي",
  ],
  "أخشاب": [
    "خشب سويدي",
    "خشب زان",
    "خشب ماهوجني (مقنو)",
    "خشب MDF",
    "خشب HDF",
    "خشب أبلكاش (بلايود)",
    "خشب كونتر",
    "خشب OSB",
    "ديكور خشبي (كلادينج)",
  ],
}

/** Flat list of all main category names — used for supplier specialization picker */
export const PREDEFINED_CATEGORIES = Object.keys(CATEGORIES_DATA)

export const SAUDI_CITIES = [
  "الرياض", "جدة", "مكة المكرمة", "المدينة المنورة", "الدمام", "الخبر", "الظهران",
  "الأحساء", "الجبيل", "تبوك", "حائل", "القصيم", "بريدة", "عنيزة", "أبها", "خميس مشيط",
  "جازان", "نجران", "الباحة", "سكاكا", "عرعر"
]

export const CATEGORIES_EN: Record<string, string> = {
  "حديد ومعادن": "Iron & Metals",
  "أسمنت وخرسانة": "Cement & Concrete",
  "طوب وبلوك": "Bricks & Blocks",
  "أرضيات وتشطيبات": "Flooring & Finishes",
  "أبواب ونوافذ": "Doors & Windows",
  "كهرباء وإنارة": "Electrical & Lighting",
  "أدوات صحية وسباكة": "Sanitary Ware & Plumbing",
  "عزل وأسقف": "Insulation & Roofing",
  "دهانات وألوان": "Paints & Colors",
  "جبس وأسقف مستعارة": "Gypsum & False Ceilings",
  "خرسانة جاهزة ومواد خام": "Ready Mix Concrete & Raw Materials",
  "معدات وآليات": "Equipment & Machinery",
  "مواد لاصقة وكيميائية": "Adhesives & Chemicals",
  "حدادة ومصنوعات معدنية": "Blacksmithing & Metal Works",
  "تكييف وتهوية (HVAC)": "HVAC",
  "أخشاب": "Wood",
}

export const CITIES_EN: Record<string, string> = {
  "الرياض": "Riyadh",
  "جدة": "Jeddah",
  "مكة المكرمة": "Makkah",
  "المدينة المنورة": "Madinah",
  "الدمام": "Dammam",
  "الخبر": "Khobar",
  "الظهران": "Dhahran",
  "الأحساء": "Al Ahsa",
  "الجبيل": "Jubail",
  "تبوك": "Tabuk",
  "حائل": "Hail",
  "القصيم": "Qassim",
  "بريدة": "Buraidah",
  "عنيزة": "Unaizah",
  "أبها": "Abha",
  "خميس مشيط": "Khamis Mushait",
  "جازان": "Jazan",
  "نجران": "Najran",
  "الباحة": "Al Baha",
  "سكاكا": "Sakaka",
  "عرعر": "Arar",
}

export const getCategoryName = (categoryAr: string, locale: string) => {
  if (locale === 'en') return CATEGORIES_EN[categoryAr] || categoryAr;
  return categoryAr;
}

export const getCityName = (cityAr: string, locale: string) => {
  if (locale === 'en') return CITIES_EN[cityAr] || cityAr;
  return cityAr;
}

export const SUBCATEGORIES_EN: Record<string, string> = {
  "حديد تسليح": "Rebar (Steel Reinforcement)",
  "حديد مجلفن": "Galvanized Steel",
  "شبك حديد (مش)": "Steel Mesh (Welded Wire)",
  "حديد مشكّل (زوايا، مواسير، صاج)": "Fabricated Steel (Angles, Pipes, Sheets)",
  "صاج مضلع": "Corrugated Sheet",
  "ستيل ستراكشر (هياكل حديدية)": "Steel Structure",
  "مسامير وبراغي ومثبتات": "Nails, Bolts & Fasteners",
  "سلك ربط": "Tie Wire",
  "حديد زهر": "Cast Iron",
  "أسمنت بورتلاندي عادي": "Ordinary Portland Cement",
  "أسمنت مقاوم للكبريتات": "Sulfate-Resistant Cement",
  "أسمنت أبيض": "White Cement",
  "أسمنت سريع التصلب": "Rapid Hardening Cement",
  "خرسانة جاهزة": "Ready Mix Concrete",
  "خرسانة مسبقة الصب (بريكاست)": "Precast Concrete",
  "إضافات خرسانية": "Concrete Admixtures",
  "أسمنت تشطيب (لياسة)": "Plastering Cement",
  "بلوك أسمنتي مفرغ": "Hollow Concrete Block",
  "بلوك أسمنتي مصمت": "Solid Concrete Block",
  "بلوك عازل (إنسوليت)": "Insulated Concrete Block",
  "طوب أحمر مفرغ": "Hollow Red Brick",
  "طوب أحمر مصمت": "Solid Red Brick",
  "طوب أحمر حراري": "Fireproof Red Brick",
  "طوب أبيض خفيف (سيبوركس)": "Lightweight White Brick (Siporex)",
  "طوب زجاجي": "Glass Block",
  "بورسلين": "Porcelain",
  "سيراميك": "Ceramic",
  "رخام طبيعي": "Natural Marble",
  "جرانيت طبيعي": "Natural Granite",
  "رخام صناعي": "Engineered Marble",
  "بلاط إسمنتي": "Cement Tile",
  "بلاط إنترلوك": "Interlock Paver",
  "باركيه خشبي": "Wooden Parquet",
  "فينيل (SPC / LVT)": "Vinyl Flooring (SPC / LVT)",
  "إيبوكسي أرضيات": "Epoxy Flooring",
  "موزاييك": "Mosaic Tile",
  "حجر طبيعي": "Natural Stone",
  "أبواب خشبية طبيعية (زان، سنديان)": "Natural Wood Doors (Beech, Oak)",
  "أبواب خشبية حشو (HDF)": "HDF Doors",
  "أبواب WPC": "WPC Doors",
  "أبواب PVC": "PVC Doors",
  "أبواب HPL": "HPL Doors",
  "أبواب حديد": "Steel Doors",
  "أبواب ألمنيوم": "Aluminum Doors",
  "أبواب مقاومة للحريق": "Fireproof Doors",
  "أبواب زجاجية": "Glass Doors",
  "أبواب كراجات (رول أب / سيكشنال)": "Garage Doors (Roll-up / Sectional)",
  "أبواب أكورديون": "Accordion Doors",
  "نوافذ ألمنيوم": "Aluminum Windows",
  "نوافذ UPVC": "UPVC Windows",
  "نوافذ زجاج مزدوج": "Double-Glazed Windows",
  "زجاج سيكوريت": "Tempered Glass",
  "زجاج عاكس": "Reflective Glass",
  "شبابيك حديد مشغول": "Wrought Iron Windows",
  "أسلاك كهربائية (NYY, NYA)": "Electrical Wires (NYY, NYA)",
  "كابلات نحاسية": "Copper Cables",
  "مفاتيح كهربائية": "Electrical Switches",
  "مقابس كهربائية": "Electrical Sockets",
  "لوحات توزيع كهربائية": "Electrical Distribution Boards",
  "قواطع كهربائية (MCB, MCCB)": "Circuit Breakers (MCB, MCCB)",
  "مواسير كهرباء PVC": "PVC Electrical Conduits",
  "مواسير كهرباء معدنية": "Metal Electrical Conduits",
  "أنظمة إنارة LED": "LED Lighting Systems",
  "كشافات إضاءة خارجية": "Outdoor Lighting Fixtures",
  "ثريات ونجف": "Chandeliers",
  "إضاءة مخفية": "Recessed Lighting",
  "أنظمة إنارة طوارئ": "Emergency Lighting Systems",
  "أنظمة طاقة شمسية": "Solar Energy Systems",
  "UPS وأنظمة طاقة احتياطية": "UPS & Backup Power Systems",
  "أنظمة إنذار حريق": "Fire Alarm Systems",
  "أنظمة كاميرات مراقبة": "CCTV Systems",
  "أنظمة إنتركم وتحكم بالدخول": "Intercom & Access Control Systems",
  "مواسير PPR": "PPR Pipes",
  "مواسير PVC صرف": "PVC Drainage Pipes",
  "مواسير نحاس": "Copper Pipes",
  "مواسير حديد مجلفن": "Galvanized Iron Pipes",
  "خلاطات مياه": "Water Mixers / Faucets",
  "أطقم حمامات (كرسي إفرنجي + مغسلة)": "Bathroom Suites (WC + Sink)",
  "كرسي عربي": "Squat Toilet",
  "بانيو": "Bathtub",
  "جاكوزي": "Jacuzzi",
  "بيديه": "Bidet",
  "شطافات": "Bidet Sprayers",
  "سخانات مياه كهربائية": "Electric Water Heaters",
  "سخانات مياه غاز": "Gas Water Heaters",
  "مضخات مياه": "Water Pumps",
  "خزانات مياه (فيبر / ستانلس / بولي إيثيلين)": "Water Tanks (Fiberglass / Stainless / Polyethylene)",
  "فلاتر مياه": "Water Filters",
  "مصافي أرضيات": "Floor Drains",
  "محابس وصمامات": "Valves & Fittings",
  "عزل مائي (رولات بيتومين)": "Waterproofing (Bitumen Rolls)",
  "عزل مائي سائل": "Liquid Waterproofing",
  "عزل حراري (فوم بولي يوريثان)": "Thermal Insulation (Polyurethane Foam)",
  "عزل حراري (صوف صخري)": "Thermal Insulation (Rock Wool)",
  "عزل حراري (بولي ستايرين XPS)": "Thermal Insulation (XPS Polystyrene)",
  "عزل صوتي": "Soundproofing",
  "ألواح ساندوتش بانل": "Sandwich Panels",
  "أسقف معدنية": "Metal Roofing",
  "أسقف قرميد": "Clay Tile Roofing",
  "ألواح بولي كربونيت": "Polycarbonate Sheets",
  "مانع رطوبة": "Damp-Proof Membrane",
  "دهان بلاستيكي (مائي) داخلي": "Interior Emulsion Paint",
  "دهان بلاستيكي خارجي": "Exterior Emulsion Paint",
  "دهان زيتي": "Oil-Based Paint",
  "دهان إيبوكسي": "Epoxy Paint",
  "دهان بولي يوريثان": "Polyurethane Paint",
  "معجون حوائط": "Wall Putty",
  "أساس (برايمر)": "Primer",
  "دهان مقاوم للحريق": "Fireproof Paint",
  "دهان مقاوم للرطوبة": "Moisture-Resistant Paint",
  "رشات ديكورية (تكستشر)": "Decorative Texture Spray",
  "ورق جدران": "Wallpaper",
  "دهان أرضيات": "Floor Paint",
  "ألواح جبس بورد عادي": "Standard Gypsum Board",
  "ألواح جبس بورد مقاوم للرطوبة": "Moisture-Resistant Gypsum Board",
  "ألواح جبس بورد مقاوم للحريق": "Fire-Resistant Gypsum Board",
  "جبس بلدي (جبس باريس)": "Plaster of Paris",
  "فواصل معدنية للجبس (أوميغا + C Channel)": "Metal Gypsum Studs (Omega + C Channel)",
  "ألواح أسقف مستعارة (معدنية)": "Metal False Ceiling Panels",
  "ألواح أسقف مستعارة (فاينل)": "Vinyl False Ceiling Panels",
  "كورنيش جبس": "Gypsum Cornice",
  "زخارف جبسية": "Gypsum Ornaments",
  "خرسانة جاهزة عادية": "Standard Ready Mix Concrete",
  "خرسانة جاهزة عالية المقاومة": "High-Strength Ready Mix Concrete",
  "رمل غسيل": "Washed Sand",
  "رمل أبيض": "White Sand",
  "بحص (حصى)": "Gravel",
  "كنكري (ركام)": "Crushed Aggregate",
  "تربة زراعية": "Topsoil",
  "ردميات": "Backfill Material",
  "رافعات (كرينات)": "Cranes",
  "حفارات": "Excavators",
  "بوب كات": "Bobcat / Skid Steer",
  "شيول": "Wheel Loader",
  "قلابات (دنبر)": "Dump Trucks",
  "خلاطات خرسانة": "Concrete Mixers",
  "مولدات كهربائية": "Generators",
  "ضواغط هواء (كمبريسر)": "Air Compressors",
  "سقالات": "Scaffolding",
  "هزازات خرسانة": "Concrete Vibrators",
  "قوالب خرسانية (فورم ورك)": "Concrete Formwork",
  "بامبات خرسانة": "Concrete Pumps",
  "لاصق بلاط (سيراميك / بورسلين)": "Tile Adhesive (Ceramic / Porcelain)",
  "لاصق رخام": "Marble Adhesive",
  "مادة وقف تسرب (سيليكون)": "Silicone Sealant",
  "فواصل تمدد": "Expansion Joints",
  "مواد تقوية خرسانة": "Concrete Reinforcement Materials",
  "إضافات خرسانية (معجّلات / مؤخرات)": "Concrete Admixtures (Accelerators / Retarders)",
  "مواد معالجة الخرسانة (كيورينغ)": "Concrete Curing Compounds",
  "مانع تسرب بولي يوريثان": "Polyurethane Sealant",
  "غراء خشب": "Wood Glue",
  "درابزين حديد": "Iron Railing",
  "درابزين ستانلس ستيل": "Stainless Steel Railing",
  "هناجر ومستودعات": "Warehouses & Sheds",
  "بوابات حديد": "Iron Gates",
  "سلالم حديد": "Iron Stairs",
  "مظلات حديد": "Iron Canopies",
  "مظلات PVC": "PVC Canopies",
  "حواجز أمنية": "Security Barriers",
  "أعمدة إنارة": "Lighting Poles",
  "وحدات تكييف سبليت": "Split AC Units",
  "وحدات تكييف مركزي": "Central AC Units",
  "وحدات تكييف كونسيلد": "Concealed AC Units",
  "مجاري هواء (دكت)": "Air Ducts",
  "مراوح شفط": "Ventilation Fans",
  "فلاتر تكييف": "AC Filters",
  "ثيرموستات ذكية": "Smart Thermostats",
  "أنظمة تبريد صحراوي": "Evaporative Cooling Systems",
  "خشب سويدي": "Swedish Pine Wood",
  "خشب زان": "Beech Wood",
  "خشب ماهوجني (مقنو)": "Mahogany Wood",
  "خشب MDF": "MDF Board",
  "خشب HDF": "HDF Board",
  "خشب أبلكاش (بلايود)": "Plywood",
  "خشب كونتر": "Blockboard",
  "خشب OSB": "OSB Board",
  "ديكور خشبي (كلادينج)": "Timber Cladding",
}

export const getSubcategoryName = (subcategoryAr: string, locale: string) => {
  if (locale === 'en') return SUBCATEGORIES_EN[subcategoryAr] || subcategoryAr;
  return subcategoryAr;
}

export const displayCategory = (catAr: string, locale: string) => {
  if (locale === 'en') return CATEGORIES_EN[catAr] || catAr;
  return catAr;
}

export const displayCity = (cityAr: string, locale: string) => {
  if (locale === 'en') return CITIES_EN[cityAr] || cityAr;
  return cityAr;
}

export const displaySubcategory = (subAr: string, locale: string) => {
  if (locale === 'en') return SUBCATEGORIES_EN[subAr] || subAr;
  return subAr;
}

export const DISTRICTS_EN: Record<string, string> = {
  // Riyadh
  "شمال الرياض": "North Riyadh",
  "جنوب الرياض": "South Riyadh",
  "شرق الرياض": "East Riyadh",
  "غرب الرياض": "West Riyadh",
  "وسط الرياض": "Central Riyadh",
  "جميع الرياض": "All of Riyadh",
  // Jeddah
  "شمال جدة": "North Jeddah",
  "جنوب جدة": "South Jeddah",
  "وسط جدة": "Central Jeddah",
  "أبحر": "Abhur",
  "جميع جدة": "All of Jeddah",
  // Makkah
  "العزيزية": "Al Aziziyah",
  "الشوقية": "Al Shawqiyyah",
  "العوالي": "Al Awali",
  "بطحاء قريش": "Batha Quraysh",
  "جميع مكة": "All of Makkah",
  // Madinah
  "الخالدية": "Al Khalidiyah",
  "الحرة الشرقية": "Al Harrah Al Sharqiyyah",
  "جميع المدينة": "All of Madinah",
  // Dammam
  "شرق الدمام": "East Dammam",
  "غرب الدمام": "West Dammam",
  "وسط الدمام": "Central Dammam",
  "جميع الدمام": "All of Dammam",
  // Khobar
  "شمال الخبر": "North Khobar",
  "الخبر الجنوبية": "South Khobar",
  "العقربية": "Al Aqrabiyah",
  "جميع الخبر": "All of Khobar",
  // Dhahran
  "حي الدانة": "Al Dana District",
  "حي الدوحة": "Al Doha District",
  "حي القصور": "Al Qusour District",
  "جميع الظهران": "All of Dhahran",
  // Al Ahsa
  "الهفوف": "Al Hofuf",
  "المبرز": "Al Mubarraz",
  "العيون": "Al Uyun",
  "العمران": "Al Umran",
  "جميع الأحساء": "All of Al Ahsa",
  // Jubail
  "الجبيل الصناعية": "Jubail Industrial City",
  "الجبيل البلد": "Jubail Old Town",
  "جميع الجبيل": "All of Jubail",
  // Tabuk
  "المروج": "Al Muruj",
  "الروضة": "Al Rawdah",
  "السليمانية": "Al Sulaymaniyah",
  "جميع تبوك": "All of Tabuk",
  // Hail
  "صديان": "Sudyan",
  "أجا": "Aja",
  "النقرة": "Al Nuqrah",
  "جميع حائل": "All of Hail",
  // Qassim
  "بريدة": "Buraidah",
  "عنيزة": "Unaizah",
  "الرس": "Al Rass",
  "البدائع": "Al Badai",
  "جميع القصيم": "All of Qassim",
  // Abha
  "حي المنسك": "Al Mansak District",
  "حي الموظفين": "Al Muwazzafin District",
  "حي الخالدية": "Al Khalidiyah District",
  "جميع أبها": "All of Abha",
  // Khamis Mushait
  "الرصراص": "Al Rasras",
  "الشباعة": "Al Shaba'ah",
  "شكر": "Shukr",
  "جميع خميس مشيط": "All of Khamis Mushait",
  // Jazan
  "حي السويس": "Al Suways District",
  "حي الروضة": "Al Rawdah District",
  "حي الشاطئ": "Al Shati District",
  "جميع جازان": "All of Jazan",
  // Najran
  "الفيصلية": "Al Faisaliyah",
  "الفهد": "Al Fahd",
  "جميع نجران": "All of Najran",
}

export const displayDistrict = (districtAr: string, locale: string) => {
  if (locale === 'en') return DISTRICTS_EN[districtAr] || districtAr;
  return districtAr;
}
